### ISSUE TITLE
Unable to login to SunnyPortal

### ISSUE THREAD

**Issue by Steff-OG** [Tommy-LSA/supoxy#2]
Hi,

is it possible to change from http to https to reenable login to sunnyportal?

Greetings
Stefan

**Comment by Tommy-LSA** [comment]
If you are using supoxy only for FHEM you should have a look on the new FHEM module. It does exactly the same as supoxy but directly, without a proxy. It uses https.
Check: http://forum.fhem.de/index.php?topic=27667.0

**Comment by Tommy-LSA** [comment]
Should work with last commit anyway
